parser: '@typescript-eslint/parser'

env:
  node: true
  es6: true
  jest: true

extends:
  - plugin:@typescript-eslint/recommended

plugins:
  - jest
  - prettier

parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'

rules:
  camelcase: off
  default-case: warn
  no-console: warn
  no-cond-assign: error
  no-else-return: warn
  no-return-assign: warn
  prettier/prettier:
    - error
    - printWidth: 120
      tabWidth: 2
      semi: true
      singleQuote: true
      trailingComma: es5
